# Site
title:              CapTerra Landscaping
bio:                'Design. Maintenance. Development.'
description:        "locally made in calgary, alberta. Custom woodworking shop that does welding, furniture fabricating, custom tables, coffee tables, stone work, carpentry, and furniture making."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zefc92.github.io/CapTerra.github.io/" # the base hostname & protocol for your site CLEAR THIS WHEN DOMAIN SETUP

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          capterralandscaping
github:             default

# personal
location:          Calgary, Alberta
phone:              Coming soon
email:              info@highlandparkfurniture.ca # 
# Other
background_image:   /images/bg.jpg 
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: "/thanks-a-bunch"

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/portfolio/:title/"
    layout: post
    author:

# Jekyll
permalink:          /portfolio/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/portfolio/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
